version: 2.1

orbs:
  cloudflare-wrangler: coryzibell/cloudflare-wrangler@volatile

jobs:
  prevent-robots:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Rename robots.txt
          command: mv public/robots.txt.disallow public/robots.txt
      - persist_to_workspace:
            root: .
            paths:
                - .
workflows:
  deploy-cloudflare-dev:
    jobs:
      - prevent-robots
      - cloudflare-wrangler/publish-wrangler-site:
          checkout: false
          attach-workspace: true
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-c8l-dev
          requires:
            - prevent-robots
          filters:
            branches:
              only:
                - develop

  deploy-cloudflare-staging:
    jobs:
      - prevent-robots:
          filters:
            branches:
              only:
                - master
      - cloudflare-wrangler/publish-wrangler-site:
          checkout: false
          attach-workspace: true
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          environment: "staging"
          requires:
            - prevent-robots
          filters:
            branches:
              only:
                - master

  deploy-cloudflare-production:
    jobs:
      - hold-for-approval:
          filters:
            branches:
              only:
                - master
          type: approval
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          type: approval
          environment: "production"
          requires:
            - hold-for-approval