version: 2.1

orbs:
  cloudflare-wrangler: coryzibell/cloudflare-wrangler@2.0.1

workflows:
  deploy-cloudflare-dev:
    jobs:
      - cloudflare-wrangler/run:
          filters:
            branches:
              only:
                - develop

  deploy-cloudflare-staging:
    jobs:
      - cloudflare-wrangler/run:
          environment: "staging"
          filters:
            branches:
              only:
                - master

  deploy-cloudflare-production:
    jobs:
      - cloudflare-wrangler/run:
          type: approval
          environment: "production"
          filters:
            branches:
              only:
                - master