version: 2.1

orbs:
  cloudflare-wrangler: coryzibell/cloudflare-wrangler@2.0.3

workflows:
  deploy-cloudflare-dev:
    jobs:
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-c8l-dev
          filters:
            branches:
              only:
                - develop

  deploy-cloudflare-staging:
    jobs:
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          environment: "staging"
          filters:
            branches:
              only:
                - master

  deploy-cloudflare-production:
    jobs:
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          type: approval
          environment: "production"
          filters:
            branches:
              only:
                - master