version: 2.1

orbs:
  cloudflare-wrangler: coryzibell/cloudflare-wrangler@volatile

jobs:
  prevent-robots:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Rename robots.txt
          command: mv public/robots.txt.disallow public/robots.txt
workflows:
  deploy-cloudflare-dev:
    jobs:
      - prevent-robots
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-c8l-dev
          filters:
            branches:
              only:
                - develop

  deploy-cloudflare-staging:
    jobs:
      - prevent-robots
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          environment: "staging"
          filters:
            branches:
              only:
                - master

  deploy-cloudflare-production:
    jobs:
      - cloudflare-wrangler/publish-wrangler-site:
          context:
            - cloudflare-workers-auth
            - cloudflare-zone-cory-bio
          type: approval
          environment: "production"
          filters:
            branches:
              only:
                - master